### ISSUE TITLE
cant create worlds

### ISSUE THREAD

**Issue by TheNimbleNinja** [MrFantiVideo/MineGate#5]
witht his mod in my pack i cant create or load worlds caues it breaks data packs

**Comment by MrFantiVideo** [comment]
Hello,

What version of mod and minecraft are you using?
Can you give more information about your pack?

Do you have errors in the game console?

**Comment by SplendidAlakey** [comment]
I have the same issue. 

MC 1.17
Fabric API 0.36.0
MineGate MoreBlocks 1.1.5

I did not check the game console at the time of the error, but here's a crash log from my server. Its a little outdated (from a couple of days ago), but I can generate a new one if you need it.

When I was trying to either load an already existing world or create a new one in single player it would fail and say something like "Unable to create the world because the data packs you selected were made for an older version of Minecraft" and offered to either try to launch vanilla or exit to title screen. Selecting vanilla would do nothing.

**Comment by MrFantiVideo** [comment]
Can you tell me what other mods are installed?

**Comment by SplendidAlakey** [comment]
Here is the client side log. In game it just says "Errors in currently selected data packs prevented the world from loading. You can either load it with only the vanilla data pack ("safe mode") or go back to the title screen and fix manually.

List of mods:

> [1.17]+Magic+Mirror+1.3.1
Adorn-2.0.0+1.17-fabric
advancements-enlarger-0.2.4
amecs-1.3.4+mc.1.17
appleskin-fabric-mc1.17-2.0.0
architects-palette-fabric-port-1.2
architectury-2.1.20-fabric
Artificial_Foliage_1.5_(FABRIC)_for_1.17
artisanat-2.1
axolotl-item-fix-1.1.0
backslot-1.1.13
backslotaddon-1.0.4
bclib-0.2.0
bedrockify-1.1.1+mc1.17
beehive-tooltips-1.3.0
beenfo-1.17-fabric0.34.9-1.3.2
betterbeds-1.2.0
better-end-0.10.1-pre
BetterMineshafts-Fabric-1.17-1.0.0
BetterStrongholds-Fabric-1.17-1.0
better-wandering-trader-1.7.0
bigbeacons-1.2.2
blockus-2.2.6+1.17.1
branders-sulfurpotassiummod-1.17-1.1.1
BuildingWands-Fabric_1.17-1.5_beta
Cardinal-Components-API-3.0.1
carrier-1.8.0
cavebiomes-0.6.3
charm-fabric-1.17-3.3.0
charmonium-fabric-1.17-3.3.0
clayrecipefabric-2.0.0
cleardespawn-1.17-fabric0.34.9-1.1.1
clientsidenoteblocks-2.0+1.17
cloth-api-2.0.54
cloth-config-5.0.34-fabric
Clumps-fabric-1.17-7.0.0.2
comforts-fabric-0.0.4-1.17
consistency_plus-1.17-0.3.3
CraftPresence-Fabric-1.17-Release-1.8.2
Croptopia-1.17-FABRIC-1.5.0
custom-portals-2.1.0
dark-loading-screen-1.6.5
DarkPaintings-fabric-1.17-3.0.6
dawn-2.0.3
dazzle-2-1.17-1.0
death_controls-1.1.0
dragonloot-1.0.8
DualRiders-1.17-1.0.5
Dynocaps-1.8.1
Earth2Java-1.7.1+1.17
elementalcreepers-1.4.0
EnchantmentDescriptions-fabric-1.17-3.0.12
expandedstorage-7.0.0-alpha.33+1.17
fabric-api-0.36.0+1.17
fabric-enchantments-0.2.1
fabric-language-kotlin-1.6.2+kotlin.1.5.20
fabrilous-updater-2.3
fallingleaves-1.7.2+1.17
FallingTree-1.17-2.12.1
fast-chest-1.2+1.17
ferritecore-3.0.1-fabric
Flonters-1.2.0+1.17
flytre_lib-1.17-0.2.18
forgottenrecipes-fabric-1.0.1
grid-1.17-fabric0.34.9-1.6.5
helpwanted-1.1.0
horse-stats-vanilla-4.1.8
indrev-1.10.0-alpha.7
inmis-2.3.1-1.17
InventoryHUD-fabric-[1.17]-3.3.2
InventorySorter-1.7.9-1.17
invisiblights-fabric-7.1+1.17
itemscroller-fabric-1.17.0-0.15.0-dev.20210608.211652
Lakeside-1.1.0+1.17
lapisreserve-1.0.8
lifts-1.1.2-BETA+1.17
light-fix-1.0.0
linkedstorage-1.3.11-1.17
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
mcda-1.6.4
mcdar-1.3.1
mcdw-3.2.4
mcsa-2.3.2-1.17
megane-5.0.1
minegate-moreblocks-1.1.5
modmenu-2.0.2
morevillagers-FABRIC-1.17-2.0.2
netherite-items-1.17-1.1.0
notenoughcrashes-3.3.1+1.17-fabric
offhandoverhaul-1.1.1
onsoulfire-1.17-2
optifabric-1.11.9
pettable-1.2.0
PlayerPig-2.0
pling-1.4.0
PresenceFootsteps-r31-1.17-rc1
preview_OptiFine_1.17_HD_U_G9_pre25
replanter-fabric-1.17-1.2
repurposed_structures_fabric-2.0.6+1.17.1
respawnablepets-1.17-2
RoughlyEnoughItems-6.0.264-alpha-fabric
scorch-1.0.1
searchable-containers-1.1.0
secretrooms-1.0.0+1.17
sihywtcamc-1.3.1+1.17.1
sihywtcamd-1.3.1+1.17.1
SimpleBackpack_Fabric-1.17-1.1.11
slight-gui-modifications-2.0.0
slotlock-1.0.4-BETA+1.17
speedyhopper-1.1-1.17-1
statuseffecttimer-1.0.2
stickyhopper-2.3-1.17-1
stitched-snow-1.0.3
tomsstorage-1.1.12
trinkets-3.0.0
true-secret-rooms-1.1.4
TweakMyClient-fabric-mc1.17-1.1.4+build.17
twigs-1.0.1
vanillaplusbiomes-0.3.2
veinmining-fabric-0.0.10-1.17
villagernames-1.17-2.0.0
Walkways-1.0.1
wanderingcollector-1.0.2+mc1.17
wirelessnetworks-1.1.1
witherite-0.0.5
wraith-silkspawners-1.0.2
wthit-fabric-3.7.0
Xaeros_Minimap_21.12.5_Fabric_1.17
XaerosWorldMap_1.14.5.1_Fabric_1.17
xlpackets-2.0-1.17
YungsApi-1.17-Fabric-11

Data packs:

> carpet_on_stairs-datapack-v5.0.0
ichphilipp-s-endcity-v1-1-1-16-2
illager-fortresses-v9-for-1-17
mcmobs-dp-1-17
New.Caves.Server.Side.Datapack
Repurposed_Structures-Disabled_Advancements-1-17-0

**Comment by MrFantiVideo** [comment]
It seems that MineGate is incompatible with one of the mods / data packs present in this list. 

Have you ever tried removing some mods / data packs to possibly see which is the problem?

I would need the name of the mod / data pack that is causing the problem to find a solution.
Given the errors I would say this is a mod that affects snow, if so please confirm to me.

**Comment by Footage2-Amply-Pounce** [comment]
Its repurposed_structures_fabric-2.0.6+1.17.1. Removing either that mod or yours lets me load in old worlds and generate new ones just fine. Is that something I should report to the developer of Repurposed structures or you can fix it from your side?

**Comment by MrFantiVideo** [comment]
We should try to see on his side if he possibly has a solution because I must admit that I do not know how to do this.
I am open to any modification to make this work.

**Comment by TelepathicGrunt** [comment]
@MrFantiVideo I see MineGate is using mixins to add new properties to vanilla blocks. This is dangerous and will make MineGate unusable with any worldgen datapack or json file that uses those blocks. Specifically, any worldgen json file that a person puts a blockstate to use will break because the blockstate codec requires every single property of the block to be listed. By adding a new property unsafely to the block, Minecraft reads these json files, sees the new property is missing, and just dies. There is a library you can depend on called [Statement](https://www.curseforge.com/minecraft/mc-mods/statement) by Virtuoel which lets you add properties to vanilla blocks without blowing up worldgen json files.

This is a common issue as many mods that do additional waterlogging blocks or vertical slabs always goes for mixins in the target block's class to add the properties. Which then kills my mod cause I use vanilla's worldgen json system lol.

In this case, the extra property to the Snow Block blew up my Snowy Dungeon processor which in 1.17+, will make the game stop and error instead of silently failing and letting you enter a broken world in 1.16.2+. 

You can use my mod [Blame](https://www.curseforge.com/minecraft/mc-mods/blame-fabric) with just Repurposed Structures and MineGate and you will see this log that shows it is the Snowy Dungeon processor that died due to new block properties: https://paste.ee/p/i4HF1

**Comment by MrFantiVideo** [comment]
Thank you very much for all the information! @TelepathicGrunt 
I will try to use Statement, but I see there is no link to any documentation, do you know if there is one?

**Comment by TelepathicGrunt** [comment]
Yeah he didn’t make docs yet got it but his discord is Virtuoel#9746 if you want to contact him on discord for more info. 

There’s these two mods that uses Statement that you can check how they use it:
https://www.curseforge.com/minecraft/mc-mods/towelette

https://www.curseforge.com/minecraft/mc-mods/more-waterlogging

**Comment by MrFantiVideo** [comment]
Not having understood how [Statement](https://www.curseforge.com/minecraft/mc-mods/statement) works and no response from the creator, I found a solution to improve.

It is now possible to disable the mixins in settings, available with [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) or in « .minecraft/config/minegate.json » by putting the option « useMixins » on false.

This disables the possibility of placing grass, flowers or snow on the plantable slabs.

**Comment by Footage2-Amply-Pounce** [comment]
@MrFantiVideo, thanks! I did manage to create a new world with mixins disabled, having both MG and RS installed. I will add the mod to my server and if I don't report back, that means everything went well there too.

I do hope that in the future, though, you will manage to make it possible to use your mod's mixins with other mods.

**Comment by Alkiasan** [comment]
Hi, this same error causes incompatibility with Croptopia. 
****************** Blame Report Worldgen Import 1.17-4.1.0-fabric ******************

 Failed to load resource file: croptopia:cashew_tree

 Reason stated: No key type in MapLike

 Possibly helpful hint (hopefully): If this is a worldgen JSON file, check out slicedlime's example datapack
   for worldgen to find what's off about the JSON: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
[
  {
    "stage": "0"
  }
]

**Comment by Alkiasan** [comment]
Note: This stops you from both creating worlds and loading into existing worlds. Making the mods unusable together.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.1](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.1))

**Comment by Footage2-Amply-Pounce** [comment]
> Fixed in the new version. ([MoreBlocks 1.2.1](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.1))

Sadly, this is still a problem in 1.2.1, logs: https://gist.github.com/Footage2-Amply-Pounce/f083d8b9ad663d91e9ed285dc1592429

The % at which it freezes seems to be either random or as soon as it generates something from either mod. I also had a world where my character was in the Nether and that one loaded successfully, but as soon as I went to the Overworld, it froze.

**Comment by MrFantiVideo** [comment]
The block properties issue is fixed, however, there is a new bug that you are talking about related to the rendering of plants on plantable slabs.
It will be fixed in the next version, I can only work on it from Thursday.

**Comment by MrFantiVideo** [comment]
> > Fixed in the new version. ([MoreBlocks 1.2.1](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.1))
> 
> Sadly, this is still a problem in 1.2.1, logs: https://gist.github.com/Footage2-Amply-Pounce/f083d8b9ad663d91e9ed285dc1592429
> 
> The % at which it freezes seems to be either random or as soon as it generates something from either mod. I also had a world where my character was in the Nether and that one loaded successfully, but as soon as I went to the Overworld, it froze.

Fixed in the new version. ([MoreBlocks 1.2.2](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.2))

**Comment by Footage2-Amply-Pounce** [comment]
> Fixed in the new version. ([MoreBlocks 1.2.2](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.2))

Yep, everything works now, thank you!
